### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by arcsector** [CybOXProject/cyboxproject.github.io#57]
Site is not working anymore (https://cyboxproject.github.io/)

**Comment by clenk** [comment]
Thanks for letting us know, @arcsector. It should be fixed now. Please note this content is rather outdated, as CybOX has been merged into STIX 2. Find out more here: http://cti-tc.github.io/

**Comment by arcsector** [comment]
Thanks for bringing it back up; CyBOX with STIX 1 never really went away; i dont see a lot of repositories for STIX 2 data and even less TAXII v2 servers. CyBOX v1 is still the industry preferred as i see it.
